### ISSUE TITLE
After I upgrade DJI SDK to 4.1.1, my project crashes

### ISSUE THREAD

**Issue by PanGuangwei** [dji-sdk/Mobile-SDK-Android#210]
- log：
====================================================
01-03 16:17:25.620 31894-31894/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: PID: 31894
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Ldji/sdk/sdkmanager/DJISDKManager$SDKManagerCallback;
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:1010)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5704)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.sdk.sdkmanager.DJISDKManager$SDKManagerCallback" on path: DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/data/app/com.ws.djilive-1/base.apk", zip file "/data/app/com.ws.djilive-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.ws.djilive-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.ws.djilive-1/lib/arm, /data/app/com.ws.djilive-1/base.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.ws.djilive-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at java.lang.Class.newInstance(Native Method) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:1010) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5704) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:156) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
===============================================================
Can anyone help me? thank you。

**Comment by Michael-DJI** [comment]
@PanGuangwei pls check if you miss following line in your Application class:
com.secneo.sdk.Helper.install(this);
pls check this tutorial:
https://developer.dji.com/mobile-sdk/documentation/android-tutorials/index.html

**Comment by PanGuangwei** [comment]
@Michael-DJI  thanks，but the problem still exists,all  my projects have the same problem, there is no problem when using 4.3.2

**Comment by EXEShirley** [comment]
@PanGuangwei Please see if this helps https://developer.dji.com/mobile-sdk/documentation/faq/index.html#after-upgrading-to-dji-android-sdk-4-4-1-my-android-project-crashes-with-java-lang-noclassdeffounderror-error-how-to-fix-it

**Comment by oliverou** [comment]
Hi @PanGuangwei , please check this FAQ explanation: <https://developer.dji.com/mobile-sdk/documentation/faq/index.html#after-upgrading-to-dji-android-sdk-4-4-1-my-android-project-crashes-with-java-lang-noclassdeffounderror-error-how-to-fix-it>, hope this helps!

**Comment by itsdebs** [comment]
**Also, you should initialize SDK class objects (Like BaseProduct.BaseProductListener, BaseComponent.ComponentListener and DJISDKManager.SDKManagerCallback) inside the onCreate() method.**
I was missing this. Thanks DJI team for being so elaborate.
I think this issue should be closed.

**Comment by itsdebs** [comment]
After trying all this, the app is still not running in Marshmallow. Running in Nougat though.

**Comment by williamjiangweiming** [comment]
java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager.DJISDKManager: void dji.sdk.sdkmanager.DJISDKManager.<init>() failed to verify: void dji.sdk.sdkmanager.DJISDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/app/com.huawei.droneplan.droneplan-1/split_lib_dependencies_apk.apk)

**Comment by williamjiangweiming** [comment]
Hi @PanGuangwei ，你解决了这个问题了吗？

**Comment by guxkung** [comment]
@williamjiangweiming  I found this issue too, but after revising my build.gradle (on multidexing, dependencies and enable lambda through java1_8 and retro_lambda plugin) and also put  DJISDKManager.getInstance().registerApp() in MainActivity.onCreate() instead of calling it from runtime. Then this problem has gone. I tried to reproduce the issue, but now I cannot.
Hope this somehow help you solve your problem though.

**Comment by manvelh** [comment]
Go to component tree and conver layout to Contraint Layout. 
![image](https://user-images.githubusercontent.com/42197045/69280561-4cdc2e00-0bac-11ea-8ef5-45d84b29c572.png)
Then Check out this link.
https://www.youtube.com/watch?v=4N4bCdyGcUc&t=3s

**Comment by kenargo** [comment]
Many of the widgets don't like constraint layout. 

You need to use three old fashion containers for now. 


⁣Get BlueMail for Android ​
